name: Cesco PR

permissions:
  contents: read
  packages: write

on:
  pull_request:
    branches:
      - main

jobs:
  service-test:
    name: Validate PR
    uses: './.github/workflows/validate.pr.yml'
    with:
      service: cesco
      working-directory: './'
      
