name: PR Validation

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write


jobs:
  test:
    name: Test PR Environment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          registry-url: "https://npm.pkg.github.com"
          cache-dependency-path: package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Run Build
        run: npm run build

    